# Site settings
title: Bossy UI
email: your-email@domain.com
description: >
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://bossyui.io/#/" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      parent: ""
      layout: "page"
  -
    scope:
      path: "pages/components"
      type: "pages"
    values:
      parent: "components"
      layout: "page"

  -
    scope:
      path: "pages/about"
      type: "pages"
    values:
      parent: "about"

  -
    scope:
      path: "_partials"
      type: "pages"
    values:
      parent: ""
